import path from "node:path";
import { readFile, writeFile } from "node:fs/promises";

/* characters.json → public.characters + public.character_variables INSERT문.
   - characters.id 는 명시 삽입(테이블이 generated BY DEFAULT 라 허용) → 변형 FK 연결에 사용.
   - icon 경로 앞에 도메인(ICON_PREFIX)을 붙여 절대 URL 로 저장.
   매핑:
     characters: id←id, name←name, first_appearance_version←min(version),
                 representative_icon_url←최신(최대 version) variant icon
     character_variables: character_id←id, eagate_cid←cid, icon_url←prefix+icon, version←version */

const ICON_PREFIX = "https://p.eagate.573.jp";

interface Variant {
  cid: string;
  icon: string;
  version: number | null;
}
interface Character {
  id: string;
  name: string;
  variants: Variant[];
}

function sqlStr(value: unknown): string {
  if (value == null) return "NULL";
  return `'${String(value).replaceAll("'", "''")}'`;
}
function sqlNum(value: unknown): string {
  if (value == null) return "NULL";
  const n = Number(value);
  return Number.isFinite(n) ? String(n) : "NULL";
}
function iconUrl(icon: string): string {
  return ICON_PREFIX + icon;
}

async function main() {
  const inPath = path.resolve("scripts/output/characters.json");
  const outPath = path.resolve("scripts/output/characters.sql");

  const characters = JSON.parse(await readFile(inPath, "utf8")) as Character[];

  const charRows: string[] = [];
  const varRows: string[] = [];
  const seenIds = new Set<string>();
  let skippedId = 0;
  let dedupedVariants = 0;

  for (const c of characters) {
    const id = String(c.id);
    if (!/^\d+$/.test(id)) {
      skippedId += 1;
      continue; // pkey(bigint) 에 넣을 수 없는 id 는 건너뜀
    }
    if (seenIds.has(id)) {
      skippedId += 1;
      continue; // 중복 id (pkey 충돌) 방지
    }
    seenIds.add(id);

    // 같은 cid 변형은 1개만
    const seenCid = new Set<string>();
    const variants = c.variants.filter((v) => {
      if (seenCid.has(v.cid)) {
        dedupedVariants += 1;
        return false;
      }
      seenCid.add(v.cid);
      return true;
    });

    const versions = variants
      .map((v) => v.version)
      .filter((v): v is number => typeof v === "number");
    const firstVersion = versions.length ? Math.min(...versions) : null;
    const repIcon = variants.length
      ? iconUrl(variants[variants.length - 1].icon)
      : null;

    charRows.push(
      `  (${id}, ${sqlStr(c.name)}, ${sqlNum(firstVersion)}, ${sqlStr(repIcon)})`
    );

    for (const v of variants) {
      varRows.push(
        `  (${id}, ${sqlStr(v.cid)}, ${sqlStr(iconUrl(v.icon))}, ${sqlNum(
          v.version
        )})`
      );
    }
  }

  const sql =
    "-- 1) characters (id 명시 삽입)\n" +
    "INSERT INTO public.characters\n" +
    "  (id, name, first_appearance_version, representative_icon_url)\n" +
    "VALUES\n" +
    charRows.join(",\n") +
    "\nON CONFLICT (id) DO NOTHING;\n\n" +
    "-- 2) character_variables (character_id = characters.id)\n" +
    "INSERT INTO public.character_variables\n" +
    "  (character_id, eagate_cid, icon_url, version)\n" +
    "VALUES\n" +
    varRows.join(",\n") +
    ";\n\n" +
    "-- 3) 명시 id 삽입 후 identity 시퀀스 정렬(이후 자동 삽입 충돌 방지)\n" +
    "SELECT setval(\n" +
    "  pg_get_serial_sequence('public.characters', 'id'),\n" +
    "  (SELECT COALESCE(MAX(id), 1) FROM public.characters)\n" +
    ");\n";

  await writeFile(outPath, sql, "utf8");

  console.log(
    `Wrote ${charRows.length} characters, ${varRows.length} variants → ${outPath}`
  );
  if (dedupedVariants) console.log(`  deduped ${dedupedVariants} same-cid variant(s)`);
  if (skippedId) console.log(`  skipped ${skippedId} character(s) with dup/invalid id`);
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
